var PSM = {
	"发动机":["PROJECT.ENGINE.LABEL", "PROJECT.TASK.BENCHMARK.VIHICLE.ENGINE_EMISSION"],
	"成本": [],
	"品牌": ["PROJECT.TASK.BENCHMARK.VIHICLE.BRAND"],
	"重量": ["PROJECT.ENGINE.MASS_TARGET", "PROJECT.TASK.BENCHMARK.INTAKE_PIPE.MASS", "PROJECT.TASK.BENCHMARK.RESONATOR.MASS", "PROJECT.TASK.BENCHMARK.AIR_FILTER.MASS", "PROJECT.TASK.BENCHMARK.OUTTAKE_PIPE.MASS"]
}
module.exports = PSM;